# Generated by Django 5.2.3 on 2025-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_alter_men_options_men_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
