# Generated by Django 5.2.3 on 2025-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_alter_men_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликована')], default=0),
        ),
    ]
