# Generated by Django 5.2.3 on 2025-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0007_tagpost_alter_men_cat_men_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='men', to='men.tagpost'),
        ),
    ]
