# Generated by Django 5.2.3 on 2025-07-31 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0010_wife_m_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='men',
            options={'ordering': ['-time_created'], 'verbose_name': 'Известные мужчины', 'verbose_name_plural': 'Известные мужчины'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='men',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='men.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='men',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='men',
            name='is_published',
            field=models.BooleanField(default=0, verbose_name='Статус публткации'),
        ),
        migrations.AlterField(
            model_name='men',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Минимум 100 символов')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='men',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='men', to='men.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='men',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='men',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновления'),
        ),
        migrations.AlterField(
            model_name='men',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='men',
            name='wife',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men', to='men.wife', verbose_name='Жена'),
        ),
    ]
