# Generated by Django 5.2.3 on 2025-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='men',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='men',
            index=models.Index(fields=['-time_created'], name='men_men_time_cr_ad832d_idx'),
        ),
    ]
