# Generated by Django 5.2.3 on 2025-07-08 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_category_men_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='men.category'),
        ),
    ]
