# Generated by Django 5.2.3 on 2025-07-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0009_wife_men_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
